### ISSUE TITLE
RootCA missing?

### ISSUE THREAD

**Issue by virgilvox** [adafruit/Adafruit_CircuitPython_AWS_IOT#7]
Looked through the code, couldnt find where the Root Certificate Authority is being set. 

I have intermittent connection issues. Sometimes I have to reload the code several times to get it to connect. Wondering if its related..

**Comment by brentru** [comment]
The RootCA for AWS IoT along with other root certs. are within the nina-firmware running on the ESP32 co-processor (https://github.com/adafruit/nina-fw/blob/master/data/roots.pem).

If you're having intermittent connection issues - please paste the exact logs from the REPL in a separate issue and I'll look into it. Those are likely due to the CircuitPython_ESP32SPI library, not this one.
